### ISSUE TITLE
Module not compatible with UTF8 characters

### ISSUE THREAD

**Issue by ana-dos-santos** [ArjenLammers/mx-serverside-barcodeqr#2]
The current Barcode module available in the Market Place is not compatible with UTF8 characters. We need to generate QR codes that supports Chinese and Croatian characters.

For this, we have already found a solution. My colleague changed the java code in the "GenerateBarcode.java" file by adding 2 more lines (see attached) and the problem was solved. We suggest that this improvement be implemented in the module available on the market place.

I opened the Request #153605 but they suggested to contact the community repo.

This ticket includes a secure attachment. Use this link to access the attached files:
https://mendix.sendsafely.com/receive/?thread=79MJ-CKLY&packageCode=hJM0LZAPcNiJJFqXUyDA4QuNblAxEzeHCAWmdnweF1k#keyCode=BYHk0DQN2TWUgH_nhroxn4Dr8tzIor__iHsAeZ6PDlc

BR
Ana

**Comment by ArjenLammers** [comment]
PR #1 has been accepted and processed in a new published version.
Thanks for the contribution!
